name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      -
      # check out our repository under $GITHUB_WORKSPACE, so our workflow can access it.
        name: Checkout 
        uses: actions/checkout@v2

      - 
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - 
        name: Build Go Project
        run: go build -v ./..
      
      -
        name: Test
        run: go test -v ./..
        
      # use our Personal Access Token (PAT) and username to log into Docker Hub
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
                
      -
      # setup Docker Buildx to create the builder instance using a BuildKit container under the hood
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
     
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/inventory-service:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/inventory-service:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/inventory-service:buildcache,mode=max